//! # Policy Decision Point (PDP)
//!
//! The PDP is the **pure, stateless** rule engine of the HISSEC*
//! architecture. Given a complete snapshot of the current request
//! context in a [`PolicyRequest`], it returns an unambiguous
//! [`PolicyResponse`] — either `Allow` or `Deny` — without ever
//! touching repositories, network, or any other side-effecting resource.
//!
//! ## Design Principle
//!
//! The PDP is intentionally kept stateless. All state it needs —
//! the requester's session ID, active role, ward, target object
//! existence flags, etc. — is provided upfront by the [`Pep`]
//! inside a [`PolicyRequest`]. This makes every decision purely
//! deterministic and trivially testable in isolation.
//!
//! ## Rule Evaluation Order
//!
//! For every operation the PDP validates the following guarantees
//! in order before calling the corresponding DYNAMO predicate:
//!
//! | Check | Rule | Meaning |
//! |-------|------|---------|
//! | Session present | **G2** | A valid session ID must exist. |
//! | Role consistent | **G3** | The active role must be assigned to this user. |
//! | Target exists | **G4** | The target object (EHR, Sensor, User) must exist. |
//! | Ward exists | **G6** | The target ward must be a registered ward. |
//! | DYNAMO predicate | Role rules | The role-specific permission is satisfied. |
//!
//! ## Example — Evaluating a Sensor Fetch
//!
//! ```rust,ignore
//! let pdp = Pdp::new();
//!
//! let mut req = PolicyRequest::new(Operation::FetchSensor);
//! req.session_id              = Some("sess-abc123".into());
//! req.requester_user_id       = Some("u-pa1".into());
//! req.active_role             = Some(RoleKind::Paramedic);
//! req.requester_ward_id       = Some("ward-icu".into());
//! req.requester_all_roles     = vec![RoleKind::Paramedic];
//! req.target_sensor_exists    = true;
//! req.target_sensor_ward_id   = Some("ward-icu".into());
//! req.target_sensor_is_critical = Some(false); // Normal sensor
//!
//! let response = pdp.evaluate(&req);
//! // => PolicyResponse::Deny("Paramedic may only fetch Critical sensors")
//! ```

use crate::policy::requests::{Operation, PolicyRequest};
use crate::policy::responses::PolicyResponse;
use crate::policy::rules::{
    SubjectSnapshot, EhrSnapshot, SensorSnapshot, TargetUserSnapshot,
    can_login, can_logout, can_read_ehr, can_fetch_sensor,
    can_add_user, can_remove_user, can_create_ehr, can_delete_ehr,
    can_assign_role, can_change_ward, g3_role_valid_for_subject,
};

/// The Policy Decision Point — a pure, stateless access control evaluator.
///
/// `Pdp` accepts a [`PolicyRequest`] containing a full snapshot of the
/// current request context and returns a [`PolicyResponse`]. It holds no
/// internal state; the same instance can be called from multiple threads
/// concurrently without synchronisation.
///
/// The actual permission predicates (`can_read_ehr`, `can_fetch_sensor`,
/// etc.) are generated by the `dynamo2rust` compiler from the formal
/// `hissec.dynamo` specification and live in `policy/rules.rs`.
pub struct Pdp;

impl Pdp {
    /// Create a new `Pdp` instance.
    ///
    /// No configuration is required. All rule logic is compiled into the
    /// binary via the DYNAMO-generated predicates in `policy/rules.rs`.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let pdp = Pdp::new();
    /// ```
    pub fn new() -> Self {
        Pdp
    }

    /// Evaluate a [`PolicyRequest`] and return an access decision.
    ///
    /// Routes the request to the appropriate private decision method
    /// based on `req.operation`, which validates the HISSEC* guarantees
    /// (G2, G3, G4, G6) before calling the DYNAMO-generated predicate.
    ///
    /// # Arguments
    ///
    /// * `req` — A [`PolicyRequest`] populated by the [`Pep`]. Fields
    ///   not relevant to the current operation are ignored; missing
    ///   required fields (e.g. absent `session_id` for a protected op)
    ///   result in an immediate `Deny`.
    ///
    /// # Returns
    ///
    /// - [`PolicyResponse::Allow`] — all applicable rules passed.
    /// - [`PolicyResponse::Deny(reason)`] — at least one rule failed;
    ///   `reason` identifies which guarantee was violated.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let response = pdp.evaluate(&req);
    ///
    /// match response {
    ///     PolicyResponse::Allow => println!("Access granted"),
    ///     PolicyResponse::Deny(r) => println!("Blocked: {r}"),
    /// }
    /// ```
    pub fn evaluate(&self, req: &PolicyRequest) -> PolicyResponse {
        match req.operation {
            Operation::Login       => self.decide_login(req),
            Operation::Logout      => self.decide_logout(req),
            Operation::ReadEhr     => self.decide_read_ehr(req),
            Operation::FetchSensor => self.decide_fetch_sensor(req),
            Operation::AddUser     => self.decide_add_user(req),
            Operation::RemoveUser  => self.decide_remove_user(req),
            Operation::CreateEhr   => self.decide_create_ehr(req),
            Operation::DeleteEhr   => self.decide_delete_ehr(req),
            Operation::AssignRole  => self.decide_assign_role(req),
            Operation::ChangeWard  => self.decide_change_ward(req),
        }
    }

    // ----------------------------------------------------------------
    // LOGIN
    //
    // Validates that the requesting user holds the role they are
    // attempting to activate. Duplicate sessions for the same user+role
    // are blocked so that a user cannot hold concurrent sessions.
    // ----------------------------------------------------------------

    /// Decide whether a login attempt is permitted.
    ///
    /// Denies if:
    /// - No role was specified in the request.
    /// - A session for this user+role is already active.
    /// - The requested role is not assigned to the user (G3 equivalent at login).
    fn decide_login(&self, req: &PolicyRequest) -> PolicyResponse {
        // G1: User must exist (caller validates this before building request).
        // The PDP trusts that the user snapshot is populated only if the user exists.
        let requested_role = match &req.login_requested_role {
            Some(r) => r,
            None => return PolicyResponse::Deny("No role requested for login".into()),
        };

        if req.login_session_already_exists {
            return PolicyResponse::Deny("Session already active for this user+role".into());
        }

        if can_login(&req.login_user_roles, requested_role) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not assigned to this user",
                requested_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // LOGOUT
    //
    // A session can always be terminated by the session owner.
    // G2 (session exists) is validated by the PEP before this is called.
    // ----------------------------------------------------------------

    /// Decide whether a logout is permitted.
    ///
    /// Denies if the subject snapshot cannot be reconstructed (missing
    /// session or user fields — indicates G2 / G1 violation).
    fn decide_logout(&self, req: &PolicyRequest) -> PolicyResponse {
        // G2: Subject must exist — validated by PEP before building request.
        let subject = match self.extract_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };

        if can_logout(&subject) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny("Cannot logout: session not owned by user".into())
        }
    }

    // ----------------------------------------------------------------
    // READ EHR
    //
    // Physicians, Nurses, and Managers may read EHRs.
    // Physicians and Nurses are restricted to their own ward (Role A).
    // Managers have unrestricted access across all wards.
    // Patients are never allowed to read EHRs.
    // ----------------------------------------------------------------

    /// Decide whether an EHR read is permitted.
    ///
    /// Enforces:
    /// - **G2** — active session required.
    /// - **G3** — active role must be assigned.
    /// - **G4** — target EHR must exist.
    /// - **Role A** — Physicians and Nurses are restricted to their own ward.
    fn decide_read_ehr(&self, req: &PolicyRequest) -> PolicyResponse {
        // G2 + G3
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: EHR exists
        if !req.target_ehr_exists {
            return PolicyResponse::Deny("EHR does not exist (G4)".into());
        }
        let ehr = EhrSnapshot {
            id: String::new(),
            ward_id: req.target_ehr_ward_id.clone().unwrap_or_default(),
        };

        if can_read_ehr(&subject, &ehr) {
            PolicyResponse::Allow
        } else if subject.active_role == crate::models::RoleKind::Patient {
            PolicyResponse::Deny("Patients may not read EHRs".into())
        } else {
            PolicyResponse::Deny("User is not in the same ward as the EHR".into())
        }
    }

    // ----------------------------------------------------------------
    // FETCH SENSOR
    //
    // Physicians and Nurses may access sensors in their own ward.
    // Paramedics may access Critical sensors only, regardless of ward
    // (Role B). All other roles are denied.
    // ----------------------------------------------------------------

    /// Decide whether a sensor fetch is permitted.
    ///
    /// Enforces:
    /// - **G2** — active session required.
    /// - **G3** — active role must be assigned.
    /// - **G4** — target sensor must exist.
    /// - **Role A** — Physicians and Nurses restricted to their ward.
    /// - **Role B** — Paramedics may only fetch `Critical` sensors.
    fn decide_fetch_sensor(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: Sensor exists
        if !req.target_sensor_exists {
            return PolicyResponse::Deny("Sensor does not exist (G4)".into());
        }
        let sensor = SensorSnapshot {
            id: String::new(),
            ward_id: req.target_sensor_ward_id.clone().unwrap_or_default(),
            sensor_type: if req.target_sensor_is_critical.unwrap_or(false) {
                crate::models::SensorType::Critical
            } else {
                crate::models::SensorType::Normal
            },
        };

        if can_fetch_sensor(&subject, &sensor) {
            PolicyResponse::Allow
        } else {
            use crate::models::RoleKind::*;
            match subject.active_role {
                Paramedic => PolicyResponse::Deny("Paramedic may only fetch Critical sensors".into()),
                Patient | Manager | Clerk => PolicyResponse::Deny(
                    format!("Role '{}' may not fetch sensors", subject.active_role)
                ),
                Physician | Nurse => PolicyResponse::Deny(
                    "User is not in the same ward as the sensor".into()
                ),
            }
        }
    }

    // ----------------------------------------------------------------
    // ADD USER
    //
    // Only Managers and Clerks may add users.
    // The target ward must be a registered ward (G6).
    // ----------------------------------------------------------------

    /// Decide whether adding a new user is permitted.
    ///
    /// Enforces **G2**, **G3**, and **G6** (target ward must exist).
    fn decide_add_user(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G6: Ward must exist
        if !req.target_ward_exists {
            return PolicyResponse::Deny("Target ward does not exist (G6)".into());
        }
        if can_add_user(&subject) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to add users",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // REMOVE USER
    //
    // Only Managers may remove users from the system.
    // The target user must exist (G4).
    // ----------------------------------------------------------------

    /// Decide whether removing an existing user is permitted.
    ///
    /// Enforces **G2**, **G3**, and **G4** (target user must exist).
    fn decide_remove_user(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: Target user exists
        if !req.target_user_exists {
            return PolicyResponse::Deny("Target user does not exist (G4)".into());
        }
        if can_remove_user(&subject) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to remove users",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // CREATE EHR
    //
    // Managers and Clerks may create EHRs.
    // The target ward must exist (G6) and the EHR ID must not already
    // be in use (treated as a G4 uniqueness constraint).
    // ----------------------------------------------------------------

    /// Decide whether creating a new EHR is permitted.
    ///
    /// Enforces **G2**, **G3**, **G4** (EHR ID must not already exist),
    /// and **G6** (target ward must exist).
    fn decide_create_ehr(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: EHR id must be unique — must not already exist
        if req.target_ehr_exists {
            return PolicyResponse::Deny("EHR with this ID already exists (G4)".into());
        }
        // G6: Ward exists
        if !req.target_ward_exists {
            return PolicyResponse::Deny("Target ward does not exist (G6)".into());
        }
        if can_create_ehr(&subject) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to create EHRs",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // DELETE EHR
    //
    // Only Managers may delete EHRs.
    // The target EHR must exist (G4).
    // ----------------------------------------------------------------

    /// Decide whether deleting an EHR is permitted.
    ///
    /// Enforces **G2**, **G3**, and **G4** (target EHR must exist).
    fn decide_delete_ehr(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: EHR must exist
        if !req.target_ehr_exists {
            return PolicyResponse::Deny("EHR does not exist (G4)".into());
        }
        if can_delete_ehr(&subject) {
            PolicyResponse::Allow
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to delete EHRs",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // ASSIGN ROLE
    //
    // Managers may assign any role. Clerks may only assign the Patient
    // role. All other roles are denied. The target user must exist (G4).
    // ----------------------------------------------------------------

    /// Decide whether assigning a role to a user is permitted.
    ///
    /// Enforces **G2**, **G3**, and **G4** (target user must exist).
    ///
    /// - Managers may assign any role.
    /// - Clerks may only assign the `Patient` role.
    fn decide_assign_role(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: Target user exists
        if !req.target_user_exists {
            return PolicyResponse::Deny("Target user does not exist (G4)".into());
        }
        let target_role = match &req.role_to_assign {
            Some(r) => r,
            None    => return PolicyResponse::Deny("No role specified to assign".into()),
        };

        if can_assign_role(&subject, target_role) {
            PolicyResponse::Allow
        } else if subject.active_role == crate::models::RoleKind::Clerk {
            PolicyResponse::Deny("Clerk may only assign the 'patient' role".into())
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to assign roles",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // CHANGE WARD
    //
    // Managers may move any user to any ward. Physicians may only move
    // Patients. All other roles are denied. Both the target user (G4)
    // and the destination ward (G6) must exist.
    // ----------------------------------------------------------------

    /// Decide whether moving a user to a different ward is permitted.
    ///
    /// Enforces **G2**, **G3**, **G4** (target user must exist), and
    /// **G6** (destination ward must exist).
    ///
    /// - Managers may move any user.
    /// - Physicians may only move users holding the `Patient` role.
    fn decide_change_ward(&self, req: &PolicyRequest) -> PolicyResponse {
        let subject = match self.extract_and_validate_subject(req) {
            Ok(s)    => s,
            Err(msg) => return PolicyResponse::Deny(msg),
        };
        // G4: Target user exists
        if !req.target_user_exists {
            return PolicyResponse::Deny("Target user does not exist (G4)".into());
        }
        // G6: New ward exists
        if !req.target_ward_exists {
            return PolicyResponse::Deny("Target ward does not exist (G6)".into());
        }
        let target = TargetUserSnapshot {
            id: req.target_user_id.clone().unwrap_or_default(),
            ward_id: req.target_user_ward_id.clone().unwrap_or_default(),
            roles: req.target_user_roles.clone(),
        };

        if can_change_ward(&subject, &target) {
            PolicyResponse::Allow
        } else if subject.active_role == crate::models::RoleKind::Physician {
            PolicyResponse::Deny("Physician may only change ward of patients".into())
        } else {
            PolicyResponse::Deny(format!(
                "Role '{}' is not allowed to change wards",
                subject.active_role
            ))
        }
    }

    // ----------------------------------------------------------------
    // Private Helpers
    // ----------------------------------------------------------------

    /// Build a [`SubjectSnapshot`] from the request without validating
    /// whether the active role is among the user's assigned roles.
    ///
    /// Used for `Login` and `Logout` where G3 does not yet apply.
    ///
    /// # Errors
    ///
    /// Returns a `String` error message if any required field
    /// (`session_id`, `requester_user_id`, or `active_role`) is absent.
    fn extract_subject(&self, req: &PolicyRequest) -> Result<SubjectSnapshot, String> {
        let session_id = req.session_id.clone()
            .ok_or_else(|| "G2: No active session".to_string())?;
        let user_id = req.requester_user_id.clone()
            .ok_or_else(|| "G1: User not found".to_string())?;
        let active_role = req.active_role.clone()
            .ok_or_else(|| "G3: No active role".to_string())?;
        Ok(SubjectSnapshot {
            session_id,
            user_id,
            active_role,
            user_ward_id: req.requester_ward_id.clone().unwrap_or_default(),
            user_roles: req.requester_all_roles.clone(),
        })
    }

    /// Build a [`SubjectSnapshot`] **and** validate G3 (active role
    /// must be present in the user's assigned role list).
    ///
    /// Used for every operation that requires an established, role-validated
    /// session — i.e., all operations except `Login`.
    ///
    /// # Errors
    ///
    /// Returns a `String` error message if G2 fields are missing or if
    /// the active role is not in the user's assigned roles (G3 violation).
    fn extract_and_validate_subject(&self, req: &PolicyRequest) -> Result<SubjectSnapshot, String> {
        let subject = self.extract_subject(req)?;
        // G3: Active role must be in user's assigned roles
        if !g3_role_valid_for_subject(&subject) {
            return Err(format!(
                "G3: Active role '{}' is not assigned to user",
                subject.active_role
            ));
        }
        Ok(subject)
    }
}

